### ISSUE TITLE
windows 10 多显示器截图移位Bug

### ISSUE THREAD

**Issue by ZGGSONG** [NPCDW/WpfTool#14]
## 现象

多显示器上Ctrl+F2截图时副屏截出来往右偏移，四分之三在副屏，四分之一在主屏，如下图：
![image](https://github.com/NPCDW/WpfTool/assets/49741009/e16bb921-e57d-4137-95f5-7a6b0e6b7164)

## 条件

- Windows 10 专业版 22H2 19045.3570
- 笔记本外接显示器，副屏，1920x1080 125%
- 主显示器，主屏，2560x1080 100%

1. 如果副屏调整成100%就没有问题，不管分辨率是多少。
2. 如果主屏和副屏同时调整成125%问题也消失了。
3. 副：125%、主：100% 副屏截图往右下偏移
4. 副：125%、主：150% 副屏截图往左上偏移
5. 好像在windows11上没有这个问题(没有详细测试)

**Comment by NPCDW** [comment]
我的环境和你的完全一样，不管是系统版本，还是笔记本和显示器的主副屏屏幕素质，都完全一样，但是我并没有你的问题，然后当我切换成你的合并请求后，出现了你截图的问题，你再看一下代码和演示，是不是真的有问题

**Comment by ZGGSONG** [comment]
我回家了以后在win11上  发现了   你原始的代码稳定触发bug，当然我后续改的也稳定触发BUG
我在家里面的电脑是笔记本2560*1440、150%、副屏
显示器3840*2160、175%、主屏

**Comment by ZGGSONG** [comment]
> 我回家了以后在win11上 发现了 你原始的代码稳定触发bug，当然我后续改的也稳定触发BUG 我在家里面的电脑是笔记本2560_1440、150%、副屏 显示器3840_2160、175%、主屏

WPFTool 的bug是在Visual Studio 2022 (版本 17.7.5)调试时出现的，打包成exe后在运行就没有bug

**Comment by NPCDW** [comment]
我上次出现这种问题是因为程序启动后 `dpi` 取到的总是 `1` ，你在你改的那行代码上面几行调试一下，看看每个屏幕获取到的 `dpi` 是不是都是 `1`

**Comment by ZGGSONG** [comment]
> 我上次出现这种问题是因为程序启动后 `dpi` 取到的总是 `1` ，你在你改的那行代码上面几行调试一下，看看每个屏幕获取到的 `dpi` 是不是都是 `1`

不是，我在 `app.manifest` 配置了 DPI感知，debug获取到的Scale是正确的，

> [https://blog.walterlv.com/post/windows-high-dpi-development-for-wpf.html](https://blog.walterlv.com/post/windows-high-dpi-development-for-wpf.html)

```xml
 <application xmlns="urn:schemas-microsoft-com:asm.v3">
   <windowsSettings>
	<dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitor</dpiAwareness>
	<dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
   </windowsSettings>
 </application>
```

家里拿了另外一台win10测试，好像也没问题，似乎是公司那台带鱼屏显示器上才会出现。。。
