### ISSUE TITLE
划词翻译

### ISSUE THREAD

**Issue by ZGGSONG** [NPCDW/WpfTool#3]
当我修改划词翻译快捷键为 Alt + 某按键(或者就是F2)的时候就无法触发复制，这是为啥，求教

**Comment by NPCDW** [comment]
按下划词翻译快捷键后能否弹出翻译窗口？

如果能弹框但没有读取复制的内容，尝试在其他地方按 `Ctrl + V` ，看按下划词翻译快捷键后是否触发了 `Ctrl + C` 快捷键

如果没有弹窗，那可能是快捷键被占用了，尝试更换其他快捷键试一下

**Comment by ZGGSONG** [comment]
我试过了，有弹窗，但是没有触发复制，只要有组合键Alt参与都不行，Ctrl加别的按键也可以 就很。。。  你可以试一下

**Comment by NPCDW** [comment]
确实有这个问题，很奇怪，我看一下什么导致的

**Comment by NPCDW** [comment]
我明白了，当设置 `Alt` 键或 `Shift` 键时，按下快捷键的时候，程序立刻发送了 `Ctrl + C` 组合键，但这个时候 `Alt` 或 `Shift` 键并没有抬起，所以就变成了同时按下了 `Ctrl + Alt + C` 键，解决方案很简单，只需要在发送复制快捷键之前，先发送一个抬起所有控制键的指令即可，会在下个版本修复

**Comment by ZGGSONG** [comment]
嗦尬，感谢感谢

**Comment by NPCDW** [comment]
[`1.7.1.0`](https://github.com/NPCDW/WpfTool/releases/tag/1.7.1.0) 版本修复了这个问题
